version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - echo Start building
  build:
    commands:
      - python ci_build.py
artifacts:
  files:
    - "**/*"
  base-directory: "output"
  secondary-artifacts:
    test-results:
      base-directory: test-results
      files:
        - "*.xml"
